### ISSUE TITLE
brew install fails with wrong version number

### ISSUE THREAD

**Issue by rjcoelho** [coinbase/terraform-landscape#120] opened 2021-02-28 17:53 UTC
```
brew install terraform_landscape
==> Downloading https://homebrew.bintray.com/bottles/terr

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "terraform_landscape"
Download failed: https://homebrew.bintray.com/bottles/terraform_landscape-0.3.4.mojave.bottle.tar.gz
```

I'm using ruby from brew 
```
ruby -v 
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin18]
``

**Comment by sds** [comment] 2021-03-02 03:32
Hey @rjcoelho, I'm not able to reproduce that error.

The error you are seeing suggests that you might be sending the traffic to a proxy or the server itself was serving HTTP instead of HTTPS, which is why you are seeing an SSL error.

This has nothing to do with Terraform Landscape, so I'm going to close this issue. If you are reliably reproducing this issue, it suggests an issue with your local network configuration, or Homebrew itself.

Hope that helps!

**Closed as completed by sds** 2021-03-02 03:32 UTC
Labels: question

**Comment by rjcoelho** [comment] 2021-03-02 11:39
Its working now :)
