### ISSUE TITLE
error: Output does not contain proper preface. Use --trace to view backtrace

### ISSUE THREAD

**Issue by ozbillwang** [coinbase/terraform-landscape#24] opened 2017-08-08 05:53 UTC
## Environment

Terraform version: 0.10.0
Run on macbook with terraform binary. Didn't test within container. 

## Error:

    error: Output does not contain proper preface. Use --trace to view backtrace

trace:

```
~/.gem/ruby/2.4.0/gems/terraform_landscape-0.1.6/lib/terraform_landscape/printer.rb:45:in `process_stream': Output does not contain proper preface (TerraformLandscape::ParseError)
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/terraform_landscape-0.1.6/lib/terraform_landscape/cli.rb:48:in `print'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/terraform_landscape-0.1.6/lib/terraform_landscape/cli.rb:34:in `block (2 levels) in define_commands'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/terraform_landscape-0.1.6/lib/terraform_landscape/cli.rb:25:in `run'
	from /Users/bill.wang/.gem/ruby/2.4.0/gems/terraform_landscape-0.1.6/bin/landscape:7:in `<top (required)>'
	from /usr/local/bin/landscape:22:in `load'
	from /usr/local/bin/landscape:22:in `<main>'
```

**Comment by sds** [comment] 2017-08-08 06:11
Thanks for the report, @ozbillwang.

It would be helpful if you could provide the output from Terraform (or a snippet) that caused this so we can easily reproduce. Ideally you would run `terraform plan > output.txt` and then provide an `output.txt` that reproduces the issue with `cat output.txt | landscape`. Thanks!

**Comment by ozbillwang** [comment] 2017-08-09 00:18
@sds 

Thanks. The problem is for any tf files if run with `terraform v0.10.0`

For example,

you can create a new `main.tf` as below
```
$ mkdir new_folder
$ cd new_folder

# Create a new simple tf file as below. 

$ cat main.tf
provider "aws" {
  version = "~> 0.1"
  region  = "ap-southeast-2"
}

resource "aws_s3_bucket" "b" {
  bucket = "my_tf_test_bucket"
  acl    = "private"

  tags {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

$ terraform init

$ terraform plan |landscape
error: Output does not contain proper preface. Use --trace to view backtrace
```

**Comment by sds** [comment] 2017-08-10 23:23
This issue seems to be related to the lack of `-out` flag provided in your particular example. Fixed by #25 but let us know if that still doesn't work!

**Comment by ozbillwang** [comment] 2017-08-11 00:00
Looks not fix. 

    error: Expected one of '~', '-/+', '-', '+', '<=', "\n" at line 46, column 1 (byte 3020) after . Use --trace to view backtrace

I can't provide the company's configuration files, will do some updates and paste here.

**Comment by sds** [comment] 2017-08-11 05:05
All we need is a minimal example that reproduces the issue, @ozbillwang. Your previous example failed for a different reason (but was still a bug, so we definitely appreciate you providing it).

Again, the fastest way to get this fixed is to give us a simple output that when we run `cat output | landscape` allows us to reproduce the issue. 

We're not currently using Terraform 0.10 so would really appreciate the help here. Thanks!

**Comment by sds** [comment] 2017-08-15 04:39
#26 fixes this for me when running Terraform 0.10.0

**Closed by sds** 2017-08-15 04:39 UTC

**Comment by laughtonsm** [comment] 2018-07-27 13:09
For me, this error is generated when there are no changes to be made.  The `plan` runs fine, but not the apply.

Terraform Version: 0.11.7
Landscape Version: 0.1.18

**Comment by johansnow** [comment] 2018-09-19 10:35
Any terraform script that ends up with errors so that execution is aborted before terraform outputs
```HCL
------------------------------------------------------------------------

An execution plan has been generated and is shown below
```
I do not know exactly what output is expected by landscape, but any script I've tried that stopped short of the above would fail. On the other hand, any script that includes the above also results in additional output.

Easiest way to reproduce the landscape issue
$ echo "" | landscape
Expected: No error message from landscape
Actual: error: Output does not contain proper preface. Use --trace to view backtrace

It would make sense to see only stdout/stderr from terraform. Getting error messages from landscape in this case just adds confusion, especially considering that it's not immediately clear if the landscape error output came from terraform or landscape.
