### ISSUE TITLE
add message for terraform input variable 

### ISSUE THREAD

**Issue by youssefNM** [coinbase/terraform-landscape#27] opened 2017-08-29 12:17 UTC
First thank you for this cool tool.
## The issue 
It seems the tool does not prompt the message for input variables  , when i have a variable in my terraform code that i should pass its value in the prompt line, normally i need to see the message of which one, something like : 
```
var.db_name
  Enter a value:
 ```

**Comment by sds** [comment] 2017-09-06 04:47
Hey @youssefNM, thanks for the report.

I'm closing this as a duplicate of #18. This isn't a workflow we utilize at @coinbase, so we won't be implementing it ourselves. We'd be happy to accept a pull request adding support for this feature, however!

**Closed by sds** 2017-09-06 04:47 UTC
Labels: duplicate
